genomeassist/scheduler/urls.py
from django.conf.urls import patterns, url

from genomeassist.scheduler import views

urlpatterns = patterns('',
    url(r'^create/_container/$', views.create_aligner_container, name='create_aligner_container'),
    url(r'^create/(?P<aligner>\w+)/$', views.create_aligner, name='create_aligner'),
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete'),
    url(r'^undelete/(?P<pk>\d+)/$', views.undelete, name='undelete'),
    url(r'^view/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^view/$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
)

genomeassist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

import genomeassist.scheduler.urls
from .scheduler.forms import login_helper

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, {'extra_context': {'helper': login_helper}}, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'', include(genomeassist.scheduler.urls, namespace='scheduler')),
)

templates/genomeassist/scheduler/urls.py
from django.conf.urls import patterns, url

from genomeassist.scheduler import views

urlpatterns = patterns('',
    url(r'^create/_container/$', views.create_aligner_container, name='create_aligner_container'),
    url(r'^create/(?P<aligner>\w+)/$', views.create_aligner, name='create_aligner'),
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete'),
    url(r'^undelete/(?P<pk>\d+)/$', views.undelete, name='undelete'),
    url(r'^view/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^view/$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
)

templates/genomeassist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

import genomeassist.scheduler.urls
from .scheduler.forms import login_helper

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, {'extra_context': {'helper': login_helper}}, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'', include(genomeassist.scheduler.urls, namespace='scheduler')),
)

genomeassist/scheduler/models.py
import celery
from celery.result import AsyncResult
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from djcelery.models import TaskMeta

from .files import read_storage


class CeleryTaskWrapper(models.Model):
    """A model wrapping Celery TaskMeta data."""
    celery_task_id = models.CharField(max_length=255, null=True)

    class Meta(object):
        abstract = True

    def celery_task(self):
        """Return the TaskMeta model instance pointed to by this model
        instance, or None if there is no result yet."""
        return TaskMeta.objects.filter(task_id=self.celery_task_id).first()

    def __unicode__(self):
        if self.name:
            name = self.name
        else:
            name = u'Untitled'
        if self.celery_task_id:
            name += u' ({})'.format(self.celery_task_id)
        return name


class Job(CeleryTaskWrapper):
    """A collection of aligner tasks that operate on the same files,
    represented as a single unit in the frontend."""
    name = models.CharField(max_length=255, blank=True)
    owner = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    read = models.FileField(
        upload_to=(lambda job, fn: '{}.fq'.format(job.id)),
        storage=read_storage,
        verbose_name='Sequence data',
        help_text='A FASTQ sequence file containing the read to align '
                  'against the reference genome.')
    reference = models.FilePathField(
        verbose_name='Reference genome',
        allow_files=False,
        allow_folders=True,
        path=settings.SCHEDULER_REFERENCE_DIR)
    options = models.TextField(
        help_text='A JSON object containing a list of aligner tasks '
                  'and their associated options.')

    def save(self, *args, **kwargs):
        # Swap the read out temporarily on initial save, as the primary
        # key hasn't been set yet, and thus the read filename can't yet
        # be determined.
        if self.pk is None:
            read_ = self.read
            self.read = None
            super(Job, self).save(*args, **kwargs)
            self.read = read_
        # We now have a primary key, so it's safe to save the model
        # instance a second time, knowing that the read filename will
        # now be set properly.
        super(Job, self).save(*args, **kwargs)

    @property
    def state(self):
        """The current state of this job."""
        if self.celery_task_id:
            result = AsyncResult(id=self.celery_task_id)
            # We don't just invariably return result.state here, because
            # the Celery task pointed to by this job is the _callback_,
            # which is not started until after the child tasks have
            # finished.  Instead, we return result.state only if the
            # callback is ready (has been started), and otherwise loop
            # over the child tasks to determine whether or not they've
            # been started.
            if result.ready():
                return result.state
        for task in self.task_set.all():
            if (task.celery_task_id and
                    AsyncResult(id=task.celery_task_id).ready()):
                return celery.states.STARTED
        return celery.states.PENDING
admin.site.register(Job)


class Task(CeleryTaskWrapper):
    """Additional task-related information not provided by Celery."""
    job = models.ForeignKey(Job)
    aligner = models.CharField(max_length=15)
    name = models.CharField(max_length=255, blank=True)
    options = models.TextField(
        help_text="A JSON object containing this task's options.")

    @property
    def state(self):
        """The current state of this task."""
        if self.celery_task_id:
            return AsyncResult(id=self.celery_task_id).state
        return celery.states.PENDING
admin.site.register(Task)

genomeassist/scheduler/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit
from django import forms

from .models import Job


login_helper = FormHelper()
login_helper.form_action = 'login'
login_helper.form_class = 'form form-horizontal'
login_helper.label_class = 'col-lg-2'
login_helper.field_class = 'col-lg-10'
login_helper.layout = Layout(
    'username',
    Field('password', css_class='form-control'),
    Div(
        FormActions(
            Submit('submit', 'Log in', css_class='btn btn-primary'),
            css_class='col-lg-offset-2 col-lg-10'
        ),
        css_class='form-group'
    )
)



class JobForm(forms.ModelForm):
    class Meta(object):
        model = Job
        fields = ['name', 'read', 'reference', 'options']

    helper = FormHelper()
    helper.form_action = 'scheduler:create'
    helper.form_class = 'form form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.layout = Layout(
        'name',
        'read',
        'reference',
        'options',
        Div(
            FormActions(
                Submit('submit', 'Submit', css_class='btn btn-primary'),
                css_class='col-lg-offset-2 col-lg-10'
            ),
            css_class='form-group'
        )
    )

templates/genomeassist/scheduler/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit
from django import forms

from .models import Job


login_helper = FormHelper()
login_helper.form_action = 'login'
login_helper.form_class = 'form form-horizontal'
login_helper.label_class = 'col-lg-2'
login_helper.field_class = 'col-lg-10'
login_helper.layout = Layout(
    'username',
    Field('password', css_class='form-control'),
    Div(
        FormActions(
            Submit('submit', 'Log in', css_class='btn btn-primary'),
            css_class='col-lg-offset-2 col-lg-10'
        ),
        css_class='form-group'
    )
)



class JobForm(forms.ModelForm):
    class Meta(object):
        model = Job
        fields = ['name', 'read', 'reference', 'options']

    helper = FormHelper()
    helper.form_action = 'scheduler:create'
    helper.form_class = 'form form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.layout = Layout(
        'name',
        'read',
        'reference',
        'options',
        Div(
            FormActions(
                Submit('submit', 'Submit', css_class='btn btn-primary'),
                css_class='col-lg-offset-2 col-lg-10'
            ),
            css_class='form-group'
        )
    )

genomeassist/scheduler/views.py
from __future__ import division
import os.path

from celery.result import AsyncResult
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.views.generic import ListView

from .forms import JobForm
from .models import Job
from .tasks.aligners import aligners
from .tasks.job import start as start_job


@login_required
def create(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            job = form.save(commit=False)
            job.owner = request.user
            job.save()
            start_job(job.id)
            return HttpResponseRedirect(
                reverse('scheduler:detail', args=[job.id]))
    else:
        if 'prefill' in request.GET:
            try:
                existing_job = Job.objects.get(pk=request.GET['prefill'])
            except Job.DoesNotExist:
                raise Http404
            if existing_job.owner != request.user:
                raise PermissionDenied
            initial = {'name': (existing_job.name or 'Unnamed') + ' copy',
                       'reference': existing_job.reference,
                       'options': existing_job.options}
            form = JobForm(initial=initial)
        else:
            form = JobForm()
    return render(request, 'scheduler/create.html', {'form': form})


@login_required
def create_aligner(request, aligner):
    try:
        return render(request, 'scheduler/aligners/{}.html'.format(aligner))
    except TemplateDoesNotExist:
        raise Http404


@login_required
def create_aligner_container(request):
    return render(request, 'scheduler/create_aligner_container.html',
                  {'aligners': aligners})


@login_required
def delete(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    if request.method == 'POST':
        job.deleted = True
        job.save()
        return HttpResponseRedirect(reverse('scheduler:index'))
    return render(request, 'scheduler/delete.html', {'job': job})


@login_required
def undelete(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    if request.method == 'POST':
        job.deleted = False
        job.save()
        return HttpResponseRedirect(reverse('scheduler:detail', args=[pk]))
    return render(request, 'scheduler/undelete.html', {'job': job})


@login_required
def detail(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    with open(os.path.join(job.reference, 'genome.len')) as f:
        reference_length = int(f.read())
    return render(request, 'scheduler/detail.html',
                  {'job': job, 'reference_length': reference_length})


@login_required
def index(request):
    show_deleted = 'show_deleted' in request.GET
    jobs = Job.objects.filter(owner=request.user)
    if not show_deleted:
        jobs = jobs.filter(deleted=False)
    return render(request, 'scheduler/index.html',
                  {'jobs': jobs.order_by('-created_at'),
                   'show_deleted': show_deleted})


@login_required
def home(request):
    return render(request, 'scheduler/home.html')

templates/genomeassist/scheduler/views.py
from __future__ import division
import os.path

from celery.result import AsyncResult
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.views.generic import ListView

from .forms import JobForm
from .models import Job
from .tasks.aligners import aligners
from .tasks.job import start as start_job


@login_required
def create(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            job = form.save(commit=False)
            job.owner = request.user
            job.save()
            start_job(job.id)
            return HttpResponseRedirect(
                reverse('scheduler:detail', args=[job.id]))
    else:
        if 'prefill' in request.GET:
            try:
                existing_job = Job.objects.get(pk=request.GET['prefill'])
            except Job.DoesNotExist:
                raise Http404
            if existing_job.owner != request.user:
                raise PermissionDenied
            initial = {'name': (existing_job.name or 'Unnamed') + ' copy',
                       'reference': existing_job.reference,
                       'options': existing_job.options}
            form = JobForm(initial=initial)
        else:
            form = JobForm()
    return render(request, 'scheduler/create.html', {'form': form})


@login_required
def create_aligner(request, aligner):
    try:
        return render(request, 'scheduler/aligners/{}.html'.format(aligner))
    except TemplateDoesNotExist:
        raise Http404


@login_required
def create_aligner_container(request):
    return render(request, 'scheduler/create_aligner_container.html',
                  {'aligners': aligners})


@login_required
def delete(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    if request.method == 'POST':
        job.deleted = True
        job.save()
        return HttpResponseRedirect(reverse('scheduler:index'))
    return render(request, 'scheduler/delete.html', {'job': job})


@login_required
def undelete(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    if request.method == 'POST':
        job.deleted = False
        job.save()
        return HttpResponseRedirect(reverse('scheduler:detail', args=[pk]))
    return render(request, 'scheduler/undelete.html', {'job': job})


@login_required
def detail(request, pk):
    try:
        job = Job.objects.get(pk=pk)
    except Job.DoesNotExist:
        raise Http404
    if job.owner != request.user:
        raise PermissionDenied
    with open(os.path.join(job.reference, 'genome.len')) as f:
        reference_length = int(f.read())
    return render(request, 'scheduler/detail.html',
                  {'job': job, 'reference_length': reference_length})


@login_required
def index(request):
    show_deleted = 'show_deleted' in request.GET
    jobs = Job.objects.filter(owner=request.user)
    if not show_deleted:
        jobs = jobs.filter(deleted=False)
    return render(request, 'scheduler/index.html',
                  {'jobs': jobs.order_by('-created_at'),
                   'show_deleted': show_deleted})


@login_required
def home(request):
    return render(request, 'scheduler/home.html')

templates/scheduler/create.html
{% extends 'default.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create New Job
{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

templates/scheduler/create_aligner_container.html
<fieldset>
  <legend>Aligner tasks</legend>

  <div class="col-lg-2">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><a href="#create_simple" data-toggle="tab">Wizard</a></li>
      <li><a href="#create_advanced" data-toggle="tab">Script</a></li>
    </ul>
  </div>

  <div class="col-lg-10">
    <div class="tab-content">
      <div class="tab-pane active" id="create_simple">
        <div class="panel-group" id="aligner_group">
          <div class="panel panel-default hidden" id="aligner_group_template">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#aligner_group">
                  Title
                </a>
              </h4>
            </div>
            <div class="panel-collapse collapse in">
              <div class="panel-body">
                <div class="form-group">
                  <label class="control-label col-lg-2">Name</label>

                  <div class="col-lg-10">
                    <input class="form-control aligner-name" type="text" placeholder="Unnamed">
                  </div>
                </div>

                <div class="aligner-options"></div>

                <div class="col-lg-12">
                  <button class="btn btn-danger">Remove this task</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-inline">
          <select id="aligner_add_type" class="form-control">
            {% for aligner in aligners %}
              <option>{{aligner}}</option>
            {% endfor %}
          </select>
          <button id="aligner_add" class="btn btn-default">Add new task</button>
        </div>
      </div>

      <div class="tab-pane" id="create_advanced">
      </div>
    </div>
  </div>
</fieldset>

templates/scheduler/delete.html
{% extends 'default.html' %}
{% load genomeassist %}
{% load humanize %}

{% block title %}
Deletion confirmation
{% endblock %}

{% block content %}
<p>Do you wish to delete <a href="{% url 'scheduler:detail' job.id %}">{% if job.name %}the job “{{job.name}}”{% else %}this unnamed job{% endif %}</a>?</p>
<form role="form" class="form-really-inline" action="{% url 'scheduler:delete' job.id %}" method="post">
{% csrf_token %}
<button class="btn btn-danger">Delete</button>
</form>
<a href="{% url 'scheduler:detail' job.id %}" class="btn btn-default">Don’t delete</a>
{% endblock %}

templates/scheduler/detail.html
{% extends 'default.html' %}
{% load genomeassist %}
{% load humanize %}

{% block title %}
{% if job.deleted %}<del>{% endif %}{% if job.name %}Job “{{job.name}}”{% else %}Unnamed job{% endif %}{% if job.deleted %}</del>{% endif %}
<small>As of <time datetime="{% now 'c' %}">{% now 'c' %}</time></small>
{% endblock %}

{% block content %}
<div class="col-lg-4">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#job-{{job.id}}" data-toggle="tab"><strong>Summary</strong></a></li>
    {% for task in job.task_set.all %}
      <li>
        <a href="#task-{{task.id}}" data-toggle="tab">
          {% if task.name %}
          {{task.aligner}} task “{{task.name}}”
          {% else %}
          Unnamed {{task.aligner}} task
          {% endif %}
        </a>
      </li>
    {% endfor %}
  </ul>
</div>

<div class="col-lg-8">
  <div class="tab-content">
    <div class="tab-pane active" id="job-{{job.id}}">
      <div class="panel-group" id="job-{{job.id}}_panels">
        <div class="panel panel-{{job.state|state_class}}">
          <div class="panel-heading">
            <h3 class="panel-title">{{job.state|lower|capfirst}}</h3>
          </div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt>Submitted</dt>
              <dd>{{job.created_at|time}}</dd>

              {% if job.celery_task %}
                <dt>Finished</dt>
                <dd>{{job.celery_task.date_done|time}}</dd>

                <dt>Job ID</dt>
                <dd>{{job.celery_task_id}}</dd>
              {% endif %}
            </dl>
          </div>
        </div> <!-- Status panel -->

        {% if job.state == 'SUCCESS' %}
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" href="#job-{{job.id}}_hitmap">Hit map ({{job.celery_task.result|length}} alignments)</a>
              </h3>
            </div>
            <div class="panel-collapse collapse in" id="job-{{job.id}}_hitmap">
              <div class="progress hitmap">
                {% for locus, qv in job.celery_task.result.iteritems %}
                  <div class="progress-bar hit"
                    data-title="Position {{locus}}"
                    data-content="QV avg. {{qv|floatformat:0}}"
                    style="left: {% ratio locus reference_length True %}%; opacity: {% ratio qv 255 %};">
                  </div>
                {% endfor %}
              </div>
            </div>
          </div> <!-- Hit map -->

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" href="#job-{{job.id}}_rusage">Resource usage statistics</a>
              </h3>
            </div>
            <div class="panel-collapse collapse in" id="job-{{job.id}}_rusage">
              <div class="panel-body">
                <div id="job-{{job.id}}_rusage_chart"></div>
                <script type="text/javascript" src="//www.google.com/jsapi"></script>
                <script>
                  google.load('visualization', '1.0', {'packages':['corechart']});
                  google.setOnLoadCallback(function () {
                    (new google.visualization.ColumnChart(
                      document.getElementById('job-{{job.id}}_rusage_chart')
                    )).draw(google.visualization.arrayToDataTable([
                      [
                        'Aligner',
                        'User CPU time',
                        'System CPU time',
                        'Peak memory resident set size',
                      ],
                      {% for task in job.task_set.all %}
                        [
                          '{% if task.name %}{{task.name|escapejs|escape}}{% else %}{{task.aligner}}{% endif %}',
                          {{task.celery_task.result.rusage.ru_utime|floatformat:3}},
                          {{task.celery_task.result.rusage.ru_stime|floatformat:3}},
                          {{task.celery_task.result.rusage.ru_maxrss_normalized}},
                        ],
                      {% endfor %}
                    ]), {
                      series: {
                        2: {targetAxisIndex: 1}
                      },
                      vAxes: [
                        {title: 'Time (seconds)', minValue: 0},
                        {title: 'Memory (bytes)', minValue: 0}
                      ]
                    });
                  });
                </script>
              </div>
            </div>
          </div> <!-- Resource usage -->
        {% endif %}
      </div> <!-- #job-{{job.id}}_panels -->

      <p>
        <form role="form" class="form-really-inline" action="{% url 'scheduler:create' %}" method="get">
          <input type="hidden" name="prefill" value="{{job.id}}">
          <button class="btn btn-default">Create a copy of this job</button>
        </form>

        {% if job.deleted %}
          <form role="form" class="form-really-inline" action="{% url 'scheduler:undelete' job.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-success">Undelete this job’s results</button>
          </form>
        {% else %}
          <form role="form" class="form-really-inline" action="{% url 'scheduler:delete' job.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger">Delete this job’s results</button>
          </form>
        {% endif %}
      </p> <!-- Action buttons -->
    </div> <!-- #job-{{job.id}} -->

    {% for task in job.task_set.all %}
      <div class="tab-pane" id="task-{{task.id}}">
        <div class="panel-group" id="task-{{task.id}}_panels">
          <div class="panel panel-{{task.state|state_class}}">
            <div class="panel-heading">
              <h3 class="panel-title">{{task.state|lower|capfirst}}</h3>
            </div>
            <div class="panel-body">
              <dl class="dl-horizontal">
                {% if task.celery_task %}
                  <dt>Finished</dt>
                  <dd>{{task.celery_task.date_done|time}}</dd>

                  <dt>Job ID</dt>
                  <dd>{{task.celery_task_id}}</dd>
                {% endif %}
              </dl>
            </div>
          </div> <!-- Status panel -->

          {% if task.state == 'SUCCESS' %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <a data-toggle="collapse" href="#task-{{task.id}}_hitmap">Hit map ({{task.celery_task.result.alignments|length}} alignments)</a>
                </h3>
              </div>
              <div class="panel-collapse collapse in" id="task-{{task.id}}_hitmap">
                <div class="progress hitmap">
                  {% for alignment in task.celery_task.result.alignments %}
                    <div class="progress-bar hit"
                      data-title="Position {{alignment.locus}}"
                      data-content="QV avg. {{alignment.quality|floatformat:0}}"
                      style="left: {% ratio alignment.locus reference_length True %}%; opacity: {% ratio alignment.quality 255 %};">
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div> <!-- Hit map -->
          {% endif %}

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" href="#task-{{task.id}}_options">Options</a>
              </h3>
            </div>
            <div class="panel-collapse collapse" id="task-{{task.id}}_options">
              <div class="panel-body">
                <pre class="pre-scrollable">{{task.options}}</pre>
              </div>
            </div>
          </div> <!-- Options -->

          {% if task.celery_task.result.out %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <a data-toggle="collapse" href="#task-{{task.id}}_result">Output</a>
                </h3>
              </div>
              <div class="panel-collapse collapse in" id="task-{{task.id}}_result">
                <div class="panel-body">
                  <pre class="pre-scrollable">{{task.celery_task.result.out}}</pre>
                </div>
              </div>
            </div> <!-- Output -->
          {% endif %}

          {% if task.state == 'SUCCESS' %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <a data-toggle="collapse" href="#task-{{task.id}}_rusage">Resource usage statistics</a>
                </h3>
              </div>
              <div class="panel-collapse collapse in" id="task-{{task.id}}_rusage">
                <table class="table">
                  <tr>
                    <th>User CPU time</th>
                    <td>{{task.celery_task.result.rusage.ru_utime|floatformat:3}} seconds</td>
                  </tr>
                  <tr>
                    <th>System CPU time</th>
                    <td>{{task.celery_task.result.rusage.ru_stime|floatformat:3}} seconds</td>
                  </tr>
                  <tr>
                    <th>Peak memory resident set size</th>
                    <td>{{task.celery_task.result.rusage.ru_maxrss_normalized|intcomma}} bytes</td>
                  </tr>
                </table>
              </div>
            </div> <!-- Resource usage -->
          {% endif %}
        </div> <!-- #task-{{task.id}}_panels -->
      </div> <!-- #task-{{task.id}} -->
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/scheduler/home.html
{% extends 'default.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
<ul class="nav nav-pills nav-stacked">
<li><a href="{% url 'scheduler:create' %}">Create a new batch alignment job</a></li>
<li><a href="{% url 'scheduler:index' %}">View existing and completed alignment jobs</a></li>
</ul>
{% endblock %}

templates/scheduler/index.html
{% extends 'default.html' %}
{% load genomeassist %}

{% block title %}
View Jobs
{% endblock %}

{% block content %}
<table class="table">
<thead>
<tr>
<th>Name</th>
<th>Status</th>
<th>Submitted</th>
<th>Finished</th>
</tr>
</thead>
<tbody>
{% for job in jobs %}
<tr>
<th><a href="{% url 'scheduler:detail' job.id %}">
{% if job.deleted %}<del>{% endif %}{% if job.name %}{{job.name}}{% else %}Unnamed{% endif %}{% if job.deleted %}</del>{% endif %}
</a></th>
<td class="text-{{job.state|state_class}}">{{job.state|lower|capfirst}}</td>
<td>{{job.created_at|time}}</td>
<td>
{% if job.celery_task.date_done %}
{{job.celery_task.date_done|time}}
{% endif %}
</td>
</tr>
{% empty %}
<tr>
<td colspan="4">You have not created any jobs.</td>
</tr>
{% endfor %}
</tbody>
</table>

<form role="form" action="{% url 'scheduler:index' %}" method="get">
{% if show_deleted %}
<button class="btn btn-default">Hide deleted jobs</button>
{% else %}
<button class="btn btn-default" name="show_deleted">Show deleted jobs</button>
{% endif %}
</form>
{% endblock %}

templates/scheduler/undelete.html
{% extends 'default.html' %}
{% load genomeassist %}
{% load humanize %}

{% block title %}
Deletion confirmation
{% endblock %}

{% block content %}
<p>Do you wish to undelete <a href="{% url 'scheduler:detail' job.id %}">{% if job.name %}the job “{{job.name}}”{% else %}this unnamed job{% endif %}</a>?</p>
<form role="form" class="form-really-inline" action="{% url 'scheduler:undelete' job.id %}" method="post">
{% csrf_token %}
<button class="btn btn-success">Undelete</button>
</form>
<a href="{% url 'scheduler:index' %}" class="btn btn-default">Don’t undelete</a>
{% endblock %}