genomeassist/scheduler/urls.py
from django.conf.urls import patterns, url

from genomeassist.scheduler import views

urlpatterns = patterns('',
    url(r'^create/_container/$', views.create_aligner_container, name='create_aligner_container'),
    url(r'^create/(?P<aligner>\w+)/$', views.create_aligner, name='create_aligner'),
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete'),
    url(r'^undelete/(?P<pk>\d+)/$', views.undelete, name='undelete'),
    url(r'^view/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^view/$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
)

genomeassist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

import genomeassist.scheduler.urls
from .scheduler.forms import login_helper

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, {'extra_context': {'helper': login_helper}}, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'', include(genomeassist.scheduler.urls, namespace='scheduler')),
)

templates/genomeassist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

import genomeassist.scheduler.urls
from .scheduler.forms import login_helper

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, {'extra_context': {'helper': login_helper}}, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'', include(genomeassist.scheduler.urls, namespace='scheduler')),
)

templates/base.html
{% load compressed %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>GenomeAssist</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
{% compressed_css 'base' %}
<!--[if lt IE 9]>
{% compressed_js 'ie8' %}
<![endif]-->
</head>

<body>
{% block body %}{% endblock %}
{% compressed_js 'base' %}
</body>
</html>

templates/default.html
{% extends 'base.html' %}

{% block body %}
<nav class="navbar navbar-default navbar-static-top" role="navigation">
<div class="container">
<div class="navbar-header">
<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{% url 'scheduler:home' %}">GenomeAssist</a>
</div>
<div class="collapse navbar-collapse">
{% if user.is_authenticated %}
<ul class="nav navbar-nav">
<li><a href="{% url 'scheduler:create' %}">Create New Job</a></li>
<li><a href="{% url 'scheduler:index' %}">View Jobs</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
{% if user.is_staff %}
<li><a href="{% url 'admin:index' %}">Admin</a></li>
{% endif %}
<li><a href="{% url 'logout' %}">Log out ({{user.username}})</a></li>
</ul>
{% endif %}
</div>
</div>
</nav>

<div class="container">
<div class="page-header">
<h1>{% block title %}{% endblock %}</h1>
</div>
{% block content %}{% endblock %}
</div>
{% endblock %}